apiVersion: apps/v1
kind: Deployment
metadata:
  name: eva-submission-ws
spec:
  replicas: 1  # Single replica for development
  template:
    spec:
      containers:
      - name: eva-submission-ws
        image: dockerhub.ebi.ac.uk/ebivariation/eva-submission-ws
        imagePullPolicy: Always
        env:
        # Outbound HTTP(S) proxy for reaching internet.
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -Dhttp.proxyHost=hh-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128
            -Dhttps.proxyHost=hh-wwwcache.ebi.ac.uk -Dhttps.proxyPort=3128
            -Dhttp.nonProxyHosts=localhost|127.*|*.cluster.local
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
