apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eva-submission-ws-stage
resources:
- namespace.yaml
- ../../base
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: dockerhub.ebi.ac.uk/ebivariation/eva-submission-ws
  newTag: dev-06189e5e
secretGenerator:
- name: eva-submission-ws-config
  files:
  - application.properties
