apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eva-seqcol-stage
resources:
- namespace.yaml
- ../../base
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: dockerhub.ebi.ac.uk/ebivariation/eva-seqcol
  newTag: dev-38291af3
secretGenerator:
- name: eva-seqcol-config
  files:
  - application.properties
