apiVersion: apps/v1
kind: Deployment
metadata:
  name: eva-web
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: eva-web
        image: dockerhub.ebi.ac.uk/ebivariation/eva-web
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"