apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
# Name the environment in the subject of the alert emails
- target:
    kind: AlertmanagerConfig
    name: eva-services
  patch: |
    - op: replace
      path: /spec/receivers/0/emailConfigs/0/headers/0/value
      value: '[EVA Kubernetes monitoring PROD] {{ .Status | title }}: {{ .CommonLabels.alertname }} on {{ .CommonLabels.eva_service }} ({{ len .Alerts.Firing }} alerts)'
