apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: count-stats

commonLabels:
  app.kubernetes.io/name: count-stats
  app.kubernetes.io/component: api

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
