apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: count-stats

labels:
- pairs:
    app.kubernetes.io/name: count-stats
    app.kubernetes.io/component: api
  includeSelectors: true

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
