apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eva-seqcol-dev
resources:
- namespace.yaml
- ../../base
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: ebivariation/eva-seqcol
  newTag: dev-ad7cb7a5
configMapGenerator:
- name: eva-seqcol-config
  behavior: replace
  envs:
  - config.env
secretGenerator:
- name: eva-seqcol-db-credentials
  envs:
  - secrets-db.env
- name: eva-seqcol-admin-credentials
  envs:
  - secrets-admin.env
