apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dgva-server

commonLabels:
  app.kubernetes.io/name: dgva-server
  app.kubernetes.io/component: api

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
