apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dgva-server-dev
resources:
- namespace.yaml
- ../../base
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: dockerhub.ebi.ac.uk/ebivariation/eva-ws
  newTag: dgva-server-dev-6a5acc24
secretGenerator:
- name: dgva-server-config
  files:
  - application.properties
