apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eva-accession-ws-dev
resources:
- namespace.yaml
- ../../base
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: dockerhub.ebi.ac.uk/ebivariation/eva-accession-ws
  newTag: dev-placeholder
secretGenerator:
- name: eva-accession-ws-config
  files:
  - application.properties
