apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: contig-alias-stage
resources:
- namespace.yaml
- ../../base
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: dockerhub.ebi.ac.uk/ebivariation/contig-alias
  newTag: dev-f6668b81
secretGenerator:
- name: contig-alias-config
  files:
  - application.properties
