apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: count-stats
spec:
  rules:
  - host: wwwint.ebi.ac.uk
    http:
      paths:
      - path: /eva/webservices/count-stats
        pathType: Prefix
        backend:
          service:
            name: count-stats
            port:
              number: 8080
