apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: count-stats-dev
resources:
- namespace.yaml
- ../../base
patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml
images:
- name: dockerhub.ebi.ac.uk/ebivariation/eva-ws
  newTag: count-stat-dev-56fc8e4a
secretGenerator:
- name: count-stats-config
  files:
  - application.properties
